### ISSUE TITLE
Padding is broken on v44

### ISSUE THREAD

**Issue by LautiLosio** [PRATAP-KUMAR/replace-activities-text#5]
After the v44 shell update the padding on the icon and text seems to be broken on my machine. I have tried uninstalling and cleaning files but the problem persists. Here's a picture:
![image](https://user-images.githubusercontent.com/38726997/234011786-676e6b1d-b03c-4ea6-a65b-7c5d8f5c0d2d.png)

**Comment by PRATAP-KUMAR** [comment]
Hi @LautiLosio, Thanks for raising this issue.
I have removed the padding intentionally, But I was thinking to implement UI for this to choose the padding based on User's wish.

Give me some time to implement this. But if you wish to make a local change in your system. Let me know, and I will give you the required changes right now so that you can have that default behaviour.

**Comment by PRATAP-KUMAR** [comment]
Hi @LautiLosio,
I have just uploaded the v17 of the extension to gnome-extensions and it got approved.

Can you test it now and then close this issue, if you are satisfied?

![image](https://user-images.githubusercontent.com/40719899/234286395-53d86406-a5b2-469c-bba7-e749faf316da.png)

Thanks
PRATAP

**Comment by LautiLosio** [comment]
I received the update before this message haha! It fixes the issue perfectly and provides a great new feature. Great work!

**Comment by PRATAP-KUMAR** [comment]
Hi @LautiLosio I have implemented Color Change Option, Can you just try it and give your comments, please?

Thanks
PRATAP

**Comment by LautiLosio** [comment]
I have tested it and it works great!
